backend:
  name: github
  repo: Chizzah/mangosrestaurant

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - name: "Food"
    label: "Food Item"
    folder: "./content/menu/food/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name of Food", name: "title", widget: "string"}
      - {label: "Supported Meals", name: "categories", widget: "list", default: ["breakfast", "lunch", "dinner"]}
      - {label: "Type of Food", name: "type", widget: "string", default: "raw bar"}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "string"}
  - name: "Drinks"
    label: "Drink Item"
    folder: "./content/menu/drinks/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name of Drink", name: "title", widget: "string"}
      - {label: "Type of Drink", name: "type", widget: "string", default: "whiskey"}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "string"}
  - name: "Dessert"
    label: "Dessert Item"
    folder: "./content/menu/dessert/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name of Dessert", name: "title", widget: "string"}
      - {label: "Type of Desert", name: "type", widget: "string", default: "chocolate"}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "string"}