backend:
  name: github
  repo: Chizzah/mangosrestaurant

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "Food"
    label: "Food Item"
    folder: "./content/food"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name of Food", name: "title", widget: "string"}
      - {label: "Supported Meals", name: "categories", widget: "list", default: ["breakfast", "lunch", "dinner", "dessert"]}
      - {label: "Type of Food", name: "type", widget: "string", default: "raw bar"}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "string"}
  - name: "Drinks"
    label: "Drink Item"
    folder: "./content/drinks"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name of Drink", name: "title", widget: "string"}
      - {label: "Drink Maker", name: "categories", widget: "hidden", default: ["drinks"]}
      - {label: "Type of Drink", name: "type", widget: "string", default: "whiskey"}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "string"}