backend:
  name: github
  repo: Chizzah/mangosrestaurant

media_folder: "static/uploads"
public_folder: "uploads"

collections:
    - label: "Breakfast"
      name: "Breakfast Item"
      create: true
      file: "content/menu/breakfast/*.md"
      fields:
        - {label: "Name of Breakfast", name: "title", widget: "string"}
        - {label: "Type of Menu Item", name: "category", widget: "hidden", default: 'Breakfast'}
        - {label: "Ingredients/Description", name: "description", widget: "text"}
        - {label: "Price", name: "price", widget: "string"}
    - label: "Starters"
      name: "Starter Item"
      create: true
      file: "content/menu/starters/*.md"
      fields:
        - {label: "Name of Starter", name: "title", widget: "string"}
        - {label: "Type of Menu Item", name: "category", widget: "hidden", default: 'Starter'}
        - {label: "Ingredients/Description", name: "description", widget: "text"}
        - {label: "Price", name: "price", widget: "string"}
    - label: "Pizza"
      name: "Pizza Item"
      create: true
      file: "content/menu/pizza/*.md"
      fields:
        - {label: "Name of Pizza", name: "title", widget: "string"}
        - {label: "Type of Menu Item", name: "category", widget: "hidden", default: 'Pizza'}
        - {label: "Ingredients/Description", name: "description", widget: "text"}
        - {label: "PiccolaPrice", name: "piccola", widget: "string"}
        - {label: "GrandePrice", name: "grande", widget: "string"}