backend:
  name: github
  repo: Chizzah/mangosrestaurant
media_folder: "static/uploads"
public_folder: "uploads"
collections:
  - label: "Menu"
    name: "Menu Items"
    files:
      - label: "Breakfast"
        name: "Breakfast Item"
        file: "content/menu/breakfast.md"
        fields:
          - name: list
            label: List
            widget: list
            fields:
              - {label: "Name of Breakfast", name: "title", widget: "string"}
              - {label: "Type of Menu Item", name: "category", widget: "hidden", default: 'Breakfast'}
              - {label: "Ingredients/Description", name: "description", widget: "text"}
              - {label: "Price", name: "price", widget: "string"}