backend:
  name: git-gateway
  repo: Chizzah/mangosrestaurant

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "Food"
    label: "Food Item"
    folder: "./content/food"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - {label: "Name of Food", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
  - name: "Drinks"
    label: "Drink Item"
    folder: "./content/drinks"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - {label: "Name of Drink", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}